name: CommandNotifier
version: ${project.version}
main: com.benzoft.commandnotifier.CommandNotifier
api-version: "1.13"
authors: [Benz56]
description: Notifies certain users of command usage.
website: benzoft.com
commands:
  commandnotifier:
    usage: /commandnotifier
    description: Get notifications when a user runs a command.
    aliases:
      - commandn
      - cnotifier
      - comnotifier
      - cn
permissions:
  commandnotifier.commands:
    description: Permission to use commands.
  commandnotifier.commands.help:
    description: Permission to use the help command.
  commandnotifier.commands.log:
    description: Permission to use the log command.
  commandnotifier.commands.toggle:
    description: Permission to use the log command.
  commandnotifier.commands.reload:
    description: Permission to use the reload command.
  commandnotifier.notify:
    default: false
  commandnotifier.update:
    default: false